server.port: 5559

logging.level:
  root: INFO
  cl.wom: DEBUG
  
app.addition: http://localhost:5557/addition
app.subtraction: http://localhost:5558/subtraction
app.multiplication: http://localhost:5559/multiplication
app.division: http://localhost:5560/division

trackia.component: MULTIPLICATION-1-0
trackia.type: API

trackia.dispatcher.class: TrackiaServerDispatcher
trackia.dispatcher.url: http://localhost:9999/journal
trackia.dispatcher.auth: http://localhost:9999/auth/signin

trackia.dispatcher.email: HELLOWORLD-1-0@trackia.app
trackia.dispatcher.password: 12345678

#Lista de modulos habilitados separados por coma
trackia.modules: SysInfoModule, SlaModule, IndexableModule
